### ISSUE TITLE
Changes to be made in website

### ISSUE THREAD

**Issue by HimaniPanwar** [MMIL/MMIL-Website-V2#8]
Try to reduce font size of text and logo in navbar and fix it to the top as due to this carousel in about page and pop-up in achievements page are not visible properly...... Add tooltips in all the pages when hovering over brand name, arrow button in the footer and another arrow button below about section(in Homepage and also change its color)....... Try to update the social sites button in contact page.

**Comment by geekayush** [comment]
@HimaniPanwar 
Tool-tips do not give a professional look. Instead of tool-tips, I added 'title' attribute.
Rest other changes have been made.
